name: flutter_networking_app
description: An app for the "Basic and advanced networking in Dart and Flutter" workshop
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  cached_network_image: 3.2.3
  dartx: 1.2.0
  dio: 5.3.2
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  intl: 0.18.1
  json_annotation: 4.8.1
  url_launcher: 6.1.12
  retrofit: 4.0.1

dev_dependencies:
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  freezed: 2.4.2
  flutter_lints: 2.0.2
  json_serializable: 6.7.1
  retrofit_generator: 7.0.8

flutter:
  uses-material-design: true
